/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;
import cleaning.*;
import java.awt.Color;
import Login.*;
/**
 *
 * @author Paras
 */
public class BServices extends javax.swing.JFrame {

    public static String user;
    /**
     * Creates new form BService
     */
    public BServices() {
        super("Our Services");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jPanel13 = new javax.swing.JPanel();
        deep = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        kitchen = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sofa = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bath = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        electrical = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        carpentry = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        plumbing = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ac = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        electrical4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        electrical3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        electrical5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        electrical6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        cockroach2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        general2 = new javax.swing.JLabel();
        termite2 = new javax.swing.JLabel();
        wood2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 685));
        setPreferredSize(new java.awt.Dimension(1000, 685));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel6.setBackground(new java.awt.Color(217, 35, 45));

        jLabel21.setBackground(new java.awt.Color(217, 35, 45));
        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel21.setText("     HOME ");
        jLabel21.setOpaque(true);
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel21MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel21MouseExited(evt);
            }
        });

        jLabel22.setBackground(new java.awt.Color(185, 30, 38));
        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel22.setText("OUR SERVICES ");
        jLabel22.setOpaque(true);
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });

        jLabel23.setBackground(new java.awt.Color(217, 35, 45));
        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel23.setText("  ABOUT US ");
        jLabel23.setOpaque(true);
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel23MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel23MouseExited(evt);
            }
        });

        jLabel24.setBackground(new java.awt.Color(217, 35, 45));
        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel24.setText("  CONTACT");
        jLabel24.setOpaque(true);
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel24MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel24MouseExited(evt);
            }
        });

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 443, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel23)
                .addGap(0, 0, 0)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel6);
        jPanel6.setBounds(0, 0, 1000, 80);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(185, 30, 38));
        jLabel5.setText(" OUR SERVICES");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(410, 90, 240, 36);

        jTabbedPane6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jTabbedPane6.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane6.setToolTipText("");
        jTabbedPane6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTabbedPane6.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jTabbedPane6.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N
        jTabbedPane6.setName(""); // NOI18N

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel13.setOpaque(false);

        deep.setBackground(new java.awt.Color(217, 35, 45));
        deep.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        deep.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        deep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/deep cleaning.png"))); // NOI18N
        deep.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        deep.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 35, 45), 2));
        deep.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deep.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deepMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(217, 35, 45));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Home Deep Cleaning");
        jLabel1.setOpaque(true);

        kitchen.setBackground(new java.awt.Color(255, 255, 255));
        kitchen.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        kitchen.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        kitchen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/kitchen clean.jpg"))); // NOI18N
        kitchen.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        kitchen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 35, 45), 2));
        kitchen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        kitchen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kitchenMouseClicked(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(217, 35, 45));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Kitchen Cleaning");
        jLabel2.setOpaque(true);

        sofa.setBackground(new java.awt.Color(255, 255, 255));
        sofa.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        sofa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sofa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/sofa.jpg"))); // NOI18N
        sofa.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        sofa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 35, 45), 2));
        sofa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sofa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sofaMouseClicked(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(217, 35, 45));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Sofa Cleaning");
        jLabel4.setOpaque(true);

        bath.setBackground(new java.awt.Color(255, 255, 255));
        bath.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        bath.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bath.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/bathroom clean.jpg"))); // NOI18N
        bath.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        bath.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 35, 45), 2));
        bath.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bath.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bathMouseClicked(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(217, 35, 45));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Bathroom Cleaning");
        jLabel3.setOpaque(true);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deep, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kitchen)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sofa, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bath, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(kitchen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(deep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(sofa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane6.addTab("  Cleaning  ", jPanel13);

        jPanel14.setDoubleBuffered(false);
        jPanel14.setOpaque(false);

        electrical.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/electrical.jpg"))); // NOI18N
        electrical.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        electrical.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 35, 45), 2));
        electrical.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        electrical.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                electricalMouseClicked(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(217, 35, 45));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Electrical Service");
        jLabel6.setOpaque(true);

        carpentry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/carpentry.jpg"))); // NOI18N
        carpentry.setToolTipText("");
        carpentry.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        carpentry.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 35, 45), 2));
        carpentry.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        carpentry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carpentryMouseClicked(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(217, 35, 45));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Plumbing Service");
        jLabel8.setOpaque(true);

        plumbing.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/Plumbing.jpg"))); // NOI18N
        plumbing.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        plumbing.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 35, 45), 2));
        plumbing.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        plumbing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plumbingMouseClicked(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(217, 35, 45));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Carpentry Service");
        jLabel9.setOpaque(true);

        ac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/ac service.jpg"))); // NOI18N
        ac.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        ac.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 35, 45), 2));
        ac.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acMouseClicked(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(217, 35, 45));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("AC Service");
        jLabel7.setOpaque(true);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(electrical))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(plumbing)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(carpentry))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ac)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(electrical, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plumbing, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(carpentry, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ac, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        jTabbedPane6.addTab("  Home Repair  ", jPanel14);

        jPanel15.setOpaque(false);

        electrical4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/fridge.jpg"))); // NOI18N
        electrical4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        electrical4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 35, 45), 2));
        electrical4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        electrical4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                electrical4MouseClicked(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(217, 35, 45));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Refrigerator Repair");
        jLabel10.setOpaque(true);

        electrical3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/tv.jpg"))); // NOI18N
        electrical3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        electrical3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 35, 45), 2));
        electrical3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        electrical3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                electrical3MouseClicked(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(217, 35, 45));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Television Repair");
        jLabel11.setOpaque(true);

        electrical5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/laptop.jpg"))); // NOI18N
        electrical5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        electrical5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 35, 45), 2));
        electrical5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        electrical5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                electrical5MouseClicked(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(217, 35, 45));
        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("PC / Laptop Repair");
        jLabel12.setOpaque(true);

        electrical6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/geyser.jpg"))); // NOI18N
        electrical6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        electrical6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 35, 45), 2));
        electrical6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        electrical6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                electrical6MouseClicked(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(217, 35, 45));
        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Geyser Repair");
        jLabel13.setOpaque(true);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(electrical4)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(electrical3)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(electrical5)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(electrical6)))))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(electrical4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(electrical3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(electrical5, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(electrical6, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        jTabbedPane6.addTab("  Appliances  ", jPanel15);

        jPanel16.setOpaque(false);

        cockroach2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/cockroach.jpg"))); // NOI18N
        cockroach2.setText("Cockroach control");
        cockroach2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        cockroach2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 35, 45), 2));
        cockroach2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cockroach2MouseClicked(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(217, 35, 45));
        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText(" Cockroach Control");
        jLabel14.setOpaque(true);

        general2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/mosquito.jpg"))); // NOI18N
        general2.setText("General Pest Control");
        general2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        general2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 35, 45), 2));
        general2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                general2MouseClicked(evt);
            }
        });

        termite2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/wood borer.jpg"))); // NOI18N
        termite2.setText("Termite Control");
        termite2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        termite2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 35, 45), 2));
        termite2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                termite2MouseClicked(evt);
            }
        });

        wood2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/termite.jpg"))); // NOI18N
        wood2.setText("Wood Borer Control");
        wood2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        wood2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(217, 35, 45), 2));
        wood2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wood2MouseClicked(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(217, 35, 45));
        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Mosquito Control");
        jLabel15.setOpaque(true);

        jLabel16.setBackground(new java.awt.Color(217, 35, 45));
        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Wood Borer Control");
        jLabel16.setOpaque(true);

        jLabel17.setBackground(new java.awt.Color(217, 35, 45));
        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("General Pest Control");
        jLabel17.setOpaque(true);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cockroach2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(general2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(termite2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(wood2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cockroach2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(general2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(termite2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wood2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        jLabel14.getAccessibleContext().setAccessibleName("Cockroach Control");

        jTabbedPane6.addTab("  Pest Control  ", jPanel16);

        getContentPane().add(jTabbedPane6);
        jTabbedPane6.setBounds(146, 132, 740, 509);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/servic.jpeg"))); // NOI18N
        getContentPane().add(jLabel18);
        jLabel18.setBounds(0, 0, 1320, 700);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        // TODO add your handling code here:
        new AHome().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        // TODO add your handling code here:
        new CAboutUs().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        // TODO add your handling code here:
        new DContact().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel24MouseClicked

    private void deepMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deepMouseClicked
        // TODO add your handling code here:
        new ACleaning().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_deepMouseClicked

    private void kitchenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kitchenMouseClicked
        // TODO add your handling code here:
        ACleaning a= new ACleaning();
        a.setVisible(true);
        this.dispose();
//        a.tabbed.setSelectedIndex(1);
    }//GEN-LAST:event_kitchenMouseClicked

    private void sofaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sofaMouseClicked
        // TODO add your handling code here:
        new ACleaning().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sofaMouseClicked

    private void bathMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bathMouseClicked
        // TODO add your handling code here:
        new ACleaning().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bathMouseClicked

    private void electricalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_electricalMouseClicked
        // TODO add your handling code here:
        new BHomeRepair().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_electricalMouseClicked

    private void plumbingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plumbingMouseClicked
        // TODO add your handling code here:
        new BHomeRepair().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_plumbingMouseClicked

    private void carpentryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carpentryMouseClicked
        // TODO add your handling code here:
        new BHomeRepair().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_carpentryMouseClicked

    private void acMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acMouseClicked
        // TODO add your handling code here:
        new BHomeRepair().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_acMouseClicked

    private void electrical4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_electrical4MouseClicked
        // TODO add your handling code here:
        new CAppliances().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_electrical4MouseClicked

    private void electrical3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_electrical3MouseClicked
        // TODO add your handling code here:
        new CAppliances().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_electrical3MouseClicked

    private void electrical5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_electrical5MouseClicked
        // TODO add your handling code here:
        new CAppliances().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_electrical5MouseClicked

    private void electrical6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_electrical6MouseClicked
        // TODO add your handling code here:
        new CAppliances().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_electrical6MouseClicked

    private void jLabel21MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseEntered
        // TODO add your handling code here:
        jLabel21.setBackground(Color.decode("#B91E26"));
    }//GEN-LAST:event_jLabel21MouseEntered

    private void jLabel21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseExited
        // TODO add your handling code here:
        jLabel21.setBackground(Color.decode("#D9232D"));
    }//GEN-LAST:event_jLabel21MouseExited

    private void jLabel23MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseEntered
        // TODO add your handling code here:
        jLabel23.setBackground(Color.decode("#B91E26"));
    }//GEN-LAST:event_jLabel23MouseEntered

    private void jLabel24MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseEntered
        // TODO add your handling code here:
        jLabel24.setBackground(Color.decode("#B91E26"));
    }//GEN-LAST:event_jLabel24MouseEntered

    private void jLabel23MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseExited
        // TODO add your handling code here:
        jLabel23.setBackground(Color.decode("#D9232D"));
    }//GEN-LAST:event_jLabel23MouseExited

    private void jLabel24MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseExited
        // TODO add your handling code here:
        jLabel24.setBackground(Color.decode("#D9232D"));
    }//GEN-LAST:event_jLabel24MouseExited

    private void cockroach2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cockroach2MouseClicked
        // TODO add your handling code here:
        new DPest().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cockroach2MouseClicked

    private void general2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_general2MouseClicked
        // TODO add your handling code here:
        new DPest().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_general2MouseClicked

    private void termite2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_termite2MouseClicked
        // TODO add your handling code here:
        new DPest().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_termite2MouseClicked

    private void wood2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wood2MouseClicked
        // TODO add your handling code here:
        new DPest().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_wood2MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        // TODO add your handling code here:
//        new BServices().setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_jLabel22MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BServices().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ac;
    private javax.swing.JLabel bath;
    private javax.swing.JLabel carpentry;
    private javax.swing.JLabel cockroach2;
    private javax.swing.JLabel deep;
    private javax.swing.JLabel electrical;
    private javax.swing.JLabel electrical3;
    private javax.swing.JLabel electrical4;
    private javax.swing.JLabel electrical5;
    private javax.swing.JLabel electrical6;
    private javax.swing.JLabel general2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JLabel kitchen;
    private javax.swing.JLabel plumbing;
    private javax.swing.JLabel sofa;
    private javax.swing.JLabel termite2;
    private javax.swing.JLabel wood2;
    // End of variables declaration//GEN-END:variables
}
